import { useState } from "react";
import { motion } from "framer-motion";
import { Download, FileText, Loader2 } from "lucide-react";
import { Button } from "./ui/button";
import { Message } from "@/hooks/useChat";
import { jsPDF } from "jspdf";
import { toast } from "@/hooks/use-toast";

interface ExportStudyNotesProps {
  messages: Message[];
  subject?: string;
  chapter?: string;
  isVisible: boolean;
}

export const ExportStudyNotes = ({ 
  messages, 
  subject = "Study Notes",
  chapter = "",
  isVisible 
}: ExportStudyNotesProps) => {
  const [isExporting, setIsExporting] = useState(false);

  if (!isVisible || messages.length === 0) return null;

  const exportToPDF = async () => {
    setIsExporting(true);

    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 20;
      const maxWidth = pageWidth - 2 * margin;
      let yPosition = 20;

      // Title
      doc.setFontSize(20);
      doc.setFont("helvetica", "bold");
      doc.text("Chalk2Chat Study Notes", margin, yPosition);
      yPosition += 10;

      // Subject/Chapter
      doc.setFontSize(14);
      doc.setFont("helvetica", "normal");
      doc.text(`${subject}${chapter ? ` - ${chapter}` : ''}`, margin, yPosition);
      yPosition += 8;

      // Date
      doc.setFontSize(10);
      doc.text(`Generated: ${new Date().toLocaleDateString()}`, margin, yPosition);
      yPosition += 15;

      // Separator
      doc.setDrawColor(200);
      doc.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 10;

      // Q&A Content
      doc.setFontSize(11);
      
      for (const message of messages) {
        // Check if we need a new page
        if (yPosition > 270) {
          doc.addPage();
          yPosition = 20;
        }

        if (message.role === 'user') {
          doc.setFont("helvetica", "bold");
          doc.setTextColor(70, 130, 180); // Steel blue for questions
          const questionLines = doc.splitTextToSize(`Q: ${message.content}`, maxWidth);
          doc.text(questionLines, margin, yPosition);
          yPosition += questionLines.length * 6 + 3;
        } else {
          doc.setFont("helvetica", "normal");
          doc.setTextColor(50, 50, 50);
          const answerLines = doc.splitTextToSize(`A: ${message.content}`, maxWidth);
          doc.text(answerLines, margin, yPosition);
          yPosition += answerLines.length * 6;

          // Add sources if available
          if (message.sources && message.sources.length > 0) {
            doc.setFontSize(9);
            doc.setTextColor(128, 128, 128);
            doc.text(`Sources: ${message.sources.join(', ')}`, margin, yPosition + 4);
            yPosition += 8;
          }

          yPosition += 10;
          doc.setFontSize(11);
        }
      }

      // Footer
      const pageCount = doc.internal.pages.length - 1;
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(
          `Page ${i} of ${pageCount} | Generated by Chalk2Chat`,
          pageWidth / 2,
          290,
          { align: 'center' }
        );
      }

      // Save
      const fileName = `chalk2chat-notes-${subject.toLowerCase().replace(/\s+/g, '-')}-${Date.now()}.pdf`;
      doc.save(fileName);

      toast({
        title: "Study Notes Exported!",
        description: `Downloaded as ${fileName}`,
      });

    } catch (error) {
      console.error('Export error:', error);
      toast({
        title: "Export Failed",
        description: "Could not generate PDF. Please try again.",
        variant: "destructive"
      });
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className="flex justify-center py-4"
    >
      <Button
        onClick={exportToPDF}
        disabled={isExporting}
        variant="outline"
        className="gap-2"
      >
        {isExporting ? (
          <>
            <Loader2 className="w-4 h-4 animate-spin" />
            Generating PDF...
          </>
        ) : (
          <>
            <Download className="w-4 h-4" />
            Export Study Notes (PDF)
          </>
        )}
      </Button>
    </motion.div>
  );
};
